### ISSUE TITLE
Gmail crashes when there are no mails in inbox.

### ISSUE THREAD

**Issue by jariz** [jariz/tabbie#54]
"Uncaught TypeError: Cannot read property 'forEach' of undefined"

**Comment by jariz** [comment]
Confirmed fixed.

**Comment by Gameboy24** [comment]
Bug has resurfaced for me 
```
extensions::lastError:133 Unchecked runtime.lastError while running identity.getAuthToken: OAuth2 request failed: Connection failed (-118).
    at gmail-auth.Polymer.signIn (chrome-extension://kckhddfnffeofnfjcpdffpeiljicclbd/tab.js:7080:33)
    at gmail-auth.events.dispatchMethod (chrome-extension://kckhddfnffeofnfjcpdffpeiljicclbd/js/libs.js:9145:38)
    at paper-button.<anonymous> (chrome-extension://kckhddfnffeofnfjcpdffpeiljicclbd/js/libs.js:10729:20)reportIfUnchecked @ extensions::lastError:133handleResponse @ extensions::sendRequest:78
Gmail.coffee:133 gapi loaded
```

Sign in button takes forever and when I click nothing happens.
